name:  🚀 Deploy hw-pages to Cloudflare Workers

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name:  🚚 检出代码仓库 / Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: ⚙ 设置 pnpm / Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          # 使用 pnpm 安装依赖
          run_install: true

      - name: ⚙ 设置 Node.js / Set up Node.js
        uses: actions/setup-node@v4
        with:
          # 选择要使用的 node 版本
          node-version: 22
          # 缓存 pnpm 依赖
          cache: pnpm

      # 运行构建脚本
      - name: ⚙ 构建 VuePress 站点 / Build VuePress site
        run: pnpm docs:build

      - name: 🚀 开始部署 / Start deployment
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: Deploy to pages branch
        run: |
          cd docs/.vuepress/dist

          git init
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add -A
          git commit -m "deploy: $(date +'%Y-%m-%d %H:%M:%S')"

          git branch -M pages
          git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git push -f origin pages
